### ISSUE TITLE
release as a gem

### ISSUE THREAD

**Issue by ohadlevy** [ingenico-group/foreman_expire_hosts#3]
Hi,

Can you please release as a gem? this would allow us to use it bundler or to package it at theforeman.org..

thanks

**Comment by nagarjuna** [comment]
Sure. I am doing some testing on this gem and will release as GEM ASAP

Regards,
Nagarjuna

**Comment by nagarjuna** [comment]
@ohadlevy I have commited changes you suggested. Please review and let me know if any more changes required.

Thanks,
Nagarjuna

**Comment by ohadlevy** [comment]
@nagarjuna from a quick look the license a gem looks fine, i did not test  or looked at other changes
you might want to close out #5 as well.

/cc @domcleal if this could be added as a plugin to our repos.

**Comment by ohadlevy** [comment]
we are also missing  a tag and official gem release.

**Comment by ahmet2mir** [comment]
Deprecated repo, see https://github.com/theforeman/foreman_expire_hosts
