### ISSUE TITLE
Licence should be GPLv3+

### ISSUE THREAD

**Issue by domcleal** [ingenico-group/foreman_expire_hosts#4]
Foreman itself is GPLv3+ and plugins are usually regarded as derivative works (IMHO), which would put it under the same licence.  I don't believe MIT is possible here.

Could you please change the LICENSE file back to GPLv3+?  It was changed to MIT in 9a402187.

**Comment by ahmet2mir** [comment]
Deprecated repo, see https://github.com/theforeman/foreman_expire_hosts
