### ISSUE TITLE
dd/mm/yyyy format is confusing

### ISSUE THREAD

**Issue by j-vizcaino** [ingenico-group/foreman_expire_hosts#6]
Using `dd/mm/yyyy` format for the `expired_on` parameter is confusing because, native english user would read it like `mm/dd/yyyy`.

Changing to ISO format `yyyy-mm-dd` would avoid such issues.

**Comment by ahmet2mir** [comment]
Deprecated repo, see https://github.com/theforeman/foreman_expire_hosts
